// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjNEbkSxlzmnSY__6zIEAaUgvZ9i4xaxo',
    appId: '1:185551144003:web:70da1803cfc27a2c6ac0f6',
    messagingSenderId: '185551144003',
    projectId: 'auth1-20df8',
    authDomain: 'auth1-20df8.firebaseapp.com',
    storageBucket: 'auth1-20df8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwK1ZQA352JpGJxk9T3U5HKOEg1sdCb9w',
    appId: '1:185551144003:android:e37148b22a0226ce6ac0f6',
    messagingSenderId: '185551144003',
    projectId: 'auth1-20df8',
    storageBucket: 'auth1-20df8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2nEWsjQBKBjghW_jeXKrEdq8T-cgHfmc',
    appId: '1:185551144003:ios:4bce7eb29d3c47606ac0f6',
    messagingSenderId: '185551144003',
    projectId: 'auth1-20df8',
    storageBucket: 'auth1-20df8.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2nEWsjQBKBjghW_jeXKrEdq8T-cgHfmc',
    appId: '1:185551144003:ios:9392051def2ead626ac0f6',
    messagingSenderId: '185551144003',
    projectId: 'auth1-20df8',
    storageBucket: 'auth1-20df8.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
